name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_APIKEY: ${{ secrets.APIKEY }}
          REACT_APP_AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          REACT_APP_DATABASEURL: ${{ secrets.DATABASEURL }}
          REACT_APP_PROJECTID: ${{ secrets.PROJECTID }}
          REACT_APP_STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
          REACT_APP_MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
          REACT_APP_APPID: ${{ secrets.APPID }}
          REACT_APP_MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
          REACT_APP_PROJECTAPI: ${{ secrets.PROJECTAPI }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
